FROM buildpack-deps:buster

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list && \
  sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list

WORKDIR /app

RUN apt-get update && \
  apt-get install -y --no-install-recommends ccache cmake libhiredis-dev libleveldb-dev libyaml-cpp-dev

VOLUME /app

CMD ["/bin/bash"]
