ARG SPIDER_VERSION

FROM ghcr.io/spider-all/spider-cplusplus:base-${SPIDER_VERSION} as base

FROM buildpack-deps:stable

WORKDIR /app

COPY --from=base /app/pkgs ./pkgs

RUN sed -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list && \
  sed -i "s/security.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list

RUN apt-get update -y && apt-get install -y --no-install-recommends ccache cmake && \
  rm -rf /var/lib/apt/lists/*
